version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /bin/bash -c "celery -A open_cosmos worker -l info"
    volumes:
      - .:/app
    depends_on:
      - web
      - redis

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /bin/bash -c "celery -A open_cosmos beat -l info"
    #entrypoint: /bin/bash -c "tail -f /dev/null"
    volumes:
      - .:/app
    depends_on:
      - celery-worker
      - redis

  data_server:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./data-server --port 28462
    ports:
       - "28462:28462"

volumes:
  postgres_data:
